export type AppScreen =
  | 'HUB'
  | 'WELCOME'
  | 'BOUND_REQUISITION'
  | 'SCANNING'
  | 'NARRATIVE'
  | 'POST_COMBAT_BOON'
  | 'SKILL_CHECK'
  | 'REST'
  | 'BLACK_MARKET'
  | 'RESOURCE_HARVEST'
  | 'EXTRACTION_REVIEW'
  | 'COMBAT'
  | 'RUN_PROGRESS'
  | 'RUN_COMPLETE'
  | 'OPERATION_DEBRIEF'
  | 'SAFEHOUSE';

export type ScanMode = 'INITIAL' | 'COMBAT_ENTRY';
